### ISSUE TITLE
MELPA release?

### ISSUE THREAD

**Issue by patrickt** [arthurcgusmao/unmodified-buffer#1]
This is a really great package—honestly, it should be the way Emacs works out of the box. Is there any chance for a MELPA release so that more people can use it?

**Comment by arthurcgusmao** [comment]
@patrickt Thanks for your suggestion, I'm glad you found this package useful.

I've just created a PR (https://github.com/melpa/melpa/pull/7853) to include this package's recipe. This was my first submission to MELPA, and a great learning process. I hope the recipe can be included soon.

This process also made me work on cleaning the code a bit. If you have any additional suggestions, please bring them in!

Cheers,
Arthur

**Comment by arthurcgusmao** [comment]
Closing since https://github.com/melpa/melpa/pull/7853 was merged. 🙌
