### ISSUE TITLE
Thoughts on writing in pure Elisp?

### ISSUE THREAD

**Issue by duckwork** [arthurcgusmao/unmodified-buffer#2]
I'm not sure how feasible this would be, but have you considered how or whether to diff the on-disk file and buffer with pure elisp (that is, without forking to another program)? It might save a bit of system time, and would be usable everywhere Emacs is. (Though it looks as though you've got the main OSes covered in your package).

**Comment by arthurcgusmao** [comment]
@duckwork This is a great idea, thanks for your suggestion. I will try to think of how that can be accomplished. Do you have ideas on how I could start?

In the meantime, I have [refactored](https://github.com/arthurcgusmao/unmodified-buffer/pull/3/commits/92e1ad33cd7eccb917b8efeacea9abde39f74c35) the existing part of the main function that compares the two files (the original file and the temp-file with the buffer contents). Therefore, implementing your suggestion now corresponds to improving only this function.

Cheers,
Arthur

**Comment by arthurcgusmao** [comment]
First thing I did was to check `diff.el`, but then I remembered it calls the system `diff` as a subroutine...

**Comment by duckwork** [comment]
I'm thinking it might include calls to `clone-buffer` and `clone-indirect-buffer`, or maybe we could look at the implementation of [apheleia](https://github.com/raxod502/apheleia), which checks if the buffer is edited before it runs a formatter.. or something.

I'll work on this this weekend and get back to you!

**Comment by duckwork** [comment]
UPDATE: Apheleia uses `diff`: https://github.com/raxod502/apheleia/blob/master/apheleia.el#L504

Not sure where to go from here. I'll keep poking at it, if I can't find something I'll just close this issue.

**Comment by duckwork** [comment]
I couldn't figure anything out, and I've installed a proper linux distribution now (so this issue no longer corresponds to me).

**Comment by arthurcgusmao** [comment]
@duckwork thanks for your efforts and for the update.
